
Shine.VoteMenu:AddPage ("RemoveBadges", function( self )
        self:AddSideButton( "1 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 1 Sand")  end)
        self:AddSideButton( "2 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 2 Sand")  end)
        self:AddSideButton( "3 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 3 Sand")  end)
        self:AddSideButton( "4 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 4 Sand")  end)
        self:AddSideButton( "5 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 5 Sand")  end)
        self:AddSideButton( "6 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 6 Sand")  end)
        self:AddSideButton( "7 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 7 Sand")  end)
        self:AddSideButton( "8 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 8 Sand")  end)
        self:AddSideButton( "9 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 9 Sand")  end)
        self:AddSideButton( "10 (500)", function() Shared.ConsoleCommand ("sh_buyremovebadge 10 Sand")  end)
          self:AddBottomButton( "Back", function()self:SetPage("SpendBadges")end) 
end)
Shine.VoteMenu:AddPage ("SpendBadges", function( self )
        self:AddTopButton( "RemoveBadges", function() self:SetPage( "RemoveBadges" ) end)
        self:AddSideButton( "cockatiel (5k)", function() Shared.ConsoleCommand ("sh_buybadge cockatiel Sand")  end)
        self:AddSideButton( "weed (5k)", function() Shared.ConsoleCommand ("sh_buybadge weed Sand")  end)
        self:AddSideButton( "pepe (5k)", function() Shared.ConsoleCommand ("sh_buybadge pepe Sand")  end)
        self:AddSideButton( "trump (5k)", function() Shared.ConsoleCommand ("sh_buybadge trump Sand")  end)
        self:AddSideButton( "sonic (5k)", function() Shared.ConsoleCommand ("sh_buybadge sonic Sand")  end)
        self:AddSideButton( "finger (5k)", function() Shared.ConsoleCommand ("sh_buybadge finger Sand")  end)
        self:AddSideButton( "pistol (5k)", function() Shared.ConsoleCommand ("sh_buybadge pistol Sand")  end)
        self:AddSideButton( "peter (5k)", function() Shared.ConsoleCommand ("sh_buybadge peter Sand")  end)
        self:AddSideButton( "feels (5k)", function() Shared.ConsoleCommand ("sh_buybadge feels Sand")  end)
        self:AddSideButton( "heart (5k)", function() Shared.ConsoleCommand ("sh_buybadge heart Sand")  end)
        

        
      --  self:AddSideButton( "Badge 2(5)", function() Shared.ConsoleCommand ("sh_buybadge Badge2 Sand")  end)
      --  self:AddSideButton( "Badge 3(5)", function() Shared.ConsoleCommand ("sh_buybadge Badge3 Sand")  end)
      --  self:AddSideButton( "Red(5)", function() Shared.ConsoleCommand ("sh_buyglow Red")  end)
        self:AddBottomButton( "Back", function()self:SetPage("SpendSand")end) 
end)


Shine.VoteMenu:AddPage ("SpendBadges", function( self )
        self:AddTopButton( "RemoveBadges", function() self:SetPage( "RemoveBadges" ) end)
        self:AddSideButton( "cockatiel (5k)", function() Shared.ConsoleCommand ("sh_buybadge cockatiel sand")  end)
        self:AddSideButton( "weed (5k)", function() Shared.ConsoleCommand ("sh_buybadge weed sand")  end)
        self:AddSideButton( "pepe (5k)", function() Shared.ConsoleCommand ("sh_buybadge pepe sand")  end)
        self:AddSideButton( "trump (5k)", function() Shared.ConsoleCommand ("sh_buybadge trump sand")  end)
        self:AddSideButton( "sonic (5k)", function() Shared.ConsoleCommand ("sh_buybadge sonic sand")  end)
        self:AddSideButton( "finger (5k)", function() Shared.ConsoleCommand ("sh_buybadge finger sand")  end)
        self:AddSideButton( "pistol (5k)", function() Shared.ConsoleCommand ("sh_buybadge pistol sand")  end)
        self:AddSideButton( "peter (5k)", function() Shared.ConsoleCommand ("sh_buybadge peter sand")  end)
        self:AddSideButton( "feels (5k)", function() Shared.ConsoleCommand ("sh_buybadge feels sand")  end)
        self:AddSideButton( "heart (5k)", function() Shared.ConsoleCommand ("sh_buybadge heart sand")  end)
        

        
      --  self:AddSideButton( "Badge 2(5)", function() Shared.ConsoleCommand ("sh_buybadge Badge2 Sand")  end)
      --  self:AddSideButton( "Badge 3(5)", function() Shared.ConsoleCommand ("sh_buybadge Badge3 Sand")  end)
      --  self:AddSideButton( "Red(5)", function() Shared.ConsoleCommand ("sh_buyglow Red")  end)
        self:AddBottomButton( "Back", function()self:SetPage("SpendSand")end) 
end)


Shine.VoteMenu:AddPage ("SpendGlowSand", function( self )
        self:AddSideButton( "Purple(5)", function() Shared.ConsoleCommand ("sh_buyglow Purple sand")  end)
        self:AddSideButton( "Green(5)", function() Shared.ConsoleCommand ("sh_buyglow Green sand")  end)
        self:AddSideButton( "Gold(5)", function() Shared.ConsoleCommand ("sh_buyglow Gold sand")  end)
      --  self:AddSideButton( "Red(5)", function() Shared.ConsoleCommand ("sh_buyglow Red")  end)
        self:AddBottomButton( "Back", function()self:SetPage("SpendSand")end) 
end)
