class 'TeleportDestination_Siege_Randomized' (TeleportDestination)
TeleportDestination_Siege_Randomized.kMapName = "teleport_destination_siege_randomized"

Shared.LinkClassToMap("TeleportDestination_Siege_Randomized", TeleportDestination_Siege_Randomized.kMapName, networkVars)